#!/usr/bin/env bash
#
# opencode-ntfy server setup — one command for all three access modes:
#
#   ./scripts/setup-server.sh local              # phone on the same Wi-Fi
#   ./scripts/setup-server.sh tailscale          # private tailnet, works anywhere
#   ./scripts/setup-server.sh cloudflare         # public URL via Cloudflare Tunnel
#   ./scripts/setup-server.sh preflight [mode]   # readiness report only (no changes)
#
# Non-interactive contract (SPEC §14.3 — consumed by install.sh and INSTALL.md):
#   --json           machine output: human text -> stderr, exactly one JSON object -> stdout
#   NTFY_PORT=8080   host port for the server (set it when the default port is taken)
#   CF_HOSTNAME=...  public hostname (required for cloudflare without a TTY)
#   NTFY_SETUP_DIR   data dir (default ~/ntfy)   NTFY_USER  admin user (default $USER)
#   exit codes: 0 ok · 2 usage · 3 missing dependency/login/input · 4 port conflict
#               5 runtime/verification failure (any other non-zero = unexpected
#               command failure; the JSON still reports the underlying status)
#
# What it does (idempotent — safe to re-run to switch modes):
#   1. writes $NTFY_SETUP_DIR/docker-compose.yml + etc/server.yml for the chosen
#      mode (auth: anonymous read-only; upstream-base-url for iOS instant push)
#   2. starts the server (Docker; on macOS: Colima) and waits for health
#   3. creates an admin user + access token (reusing an existing one if present)
#   4. mode extras: tailscale serve proxy / cloudflared tunnel + DNS + launchd
#   5. smoke-tests auth (anonymous publish must be denied) and prints your
#      opencode.json snippet + phone instructions
#
# Switching modes later: re-run this script with the other mode, then
# re-add the subscriptions on your phone (they are keyed by server URL).
#
set -euo pipefail

DATA_DIR="${NTFY_SETUP_DIR:-$HOME/ntfy}"
CF_HOSTNAME="${CF_HOSTNAME:-}"
NTFY_PORT="${NTFY_PORT:-80}"
TOKEN_LABEL="opencode-setup"
COMPOSE_MARKER="# generated by opencode-ntfy setup-server.sh"

JSON=0
CMD="setup"
MODE=""
WARNINGS=""
CHECKS_JSON=""
FLAG3=0
FLAG4=0
LOG_FD=1

# ------------------------------------------------------------------ helpers
json_str() {
  local s="${1//\\/\\\\}"
  s="${s//\"/\\\"}"
  s="${s//$'\n'/ }"
  printf '"%s"' "$s"
}
mode_json() {
  if [ -n "$MODE" ]; then json_str "$MODE"; else printf 'null'; fi
}
add_warning() { # <code> <message> — accumulated for the final --json result
  if [ -n "$WARNINGS" ]; then WARNINGS="$WARNINGS,"; fi
  WARNINGS="${WARNINGS}{\"code\":$(json_str "$1"),\"message\":$(json_str "$2")}"
}
say()  { printf '\n\033[1m== %s\033[0m\n' "$*" >&"$LOG_FD"; }
info() { printf '   %s\n' "$*" >&"$LOG_FD"; }
usage() {
  cat <<USAGE
opencode-ntfy server setup

  $0 [--json] local|tailscale|cloudflare    provision (or switch) the server
  $0 [--json] preflight [mode]              readiness report only, makes no changes

Env:
  NTFY_PORT=$NTFY_PORT     host port for the server (set it to e.g. 8080 if $NTFY_PORT is taken)
  CF_HOSTNAME=...     public hostname (required for cloudflare without a TTY)
  NTFY_SETUP_DIR      data dir (default: ~/ntfy)
  NTFY_USER           admin user (default: \$USER)

Exit codes: 0 ok · 2 usage · 3 missing dependency/login · 4 port conflict · 5 runtime
USAGE
}
die() {
  local code=5
  case "${1:-}" in
    ''|*[!0-9]*) ;;
    *) code="$1"; shift ;;
  esac
  local msg="$*"
  printf '\033[31mERROR:\033[0m %s\n' "$msg" >&2
  if [ "$JSON" = 1 ]; then
    printf '{"ok":false,"kind":%s,"mode":%s,"code":%d,"error":%s}\n' \
      "$(json_str "$CMD")" "$(mode_json)" "$code" "$(json_str "$msg")"
  fi
  exit "$code"
}

# Name of the process listening on a port ('' when free / undetectable).
port_owner() {
  local p="$1" pid=""
  if command -v lsof >/dev/null 2>&1; then
    pid="$(lsof -nP -iTCP:"$p" -sTCP:LISTEN -t 2>/dev/null | head -1 || true)"
  elif command -v ss >/dev/null 2>&1; then
    pid="$(ss -ltnp "sport = :$p" 2>/dev/null | sed -n 's/.*pid=\([0-9]*\).*/\1/p' | head -1 || true)"
  fi
  if [ -n "$pid" ]; then ps -p "$pid" -o comm= 2>/dev/null | head -1 || true; fi
}

# Run a command with a hard deadline. Needed because `tailscale serve --bg`
# BLOCKS forever when Serve isn't activated yet (it prints an activation link
# and then waits for approval that will never come in a non-interactive run).
# The perl fallback forks so bash never reports a signal-killed child.
run_with_timeout() {
  local secs="$1"; shift
  if command -v timeout >/dev/null 2>&1; then timeout "$secs" "$@"
  elif command -v gtimeout >/dev/null 2>&1; then gtimeout "$secs" "$@"
  else perl -e '
      my $secs = shift;
      my $pid = fork() // exit 127;
      if (!$pid) { exec @ARGV or exit 127 }
      local $SIG{ALRM} = sub { kill "TERM", $pid; exit 124 };
      alarm $secs;
      waitpid($pid, 0);
      my $st = $?;
      exit($st & 127 ? 128 + ($st & 127) : $st >> 8);
    ' "$secs" "$@"
  fi
}

# --------------------------------------------------------------- arguments
# Pre-scan so --json works in any position (error JSON for parse failures too).
for arg in "$@"; do
  if [ "$arg" = "--json" ]; then JSON=1; LOG_FD=2; fi
done
for arg in "$@"; do
  case "$arg" in
    --json) ;;
    preflight) CMD="preflight" ;;
    local|tailscale|cloudflare)
      if [ -n "$MODE" ] && [ "$MODE" != "$arg" ]; then
        die 2 "conflicting modes: $MODE and $arg"
      fi
      MODE="$arg"
      ;;
    -h|--help) usage; exit 0 ;;
    *) die 2 "unknown argument: $arg" ;;
  esac
done
case "$NTFY_PORT" in
  ''|*[!0-9]*) die 2 "NTFY_PORT must be a number (got: $NTFY_PORT)" ;;
esac

# In --json mode any UNEXPECTED failure must still emit the JSON error object.
if [ "$JSON" = 1 ]; then
  set -E
  trap 'rc=$?; printf "{\"ok\":false,\"kind\":%s,\"mode\":%s,\"code\":%d,\"error\":%s}\n" "$(json_str "$CMD")" "$(mode_json)" "$rc" "$(json_str "unexpected failure: $BASH_COMMAND")"' ERR
fi

# ------------------------------------------------- preflight subcommand (read-only)
check() { # <id> <ok 0/1> <hint> [value] [severity 3|4] — never exits, never changes state
  local id="$1" ok="$2" hint="${3:-}" value="${4:-}" sev="${5:-3}"
  local jok=false
  if [ "$ok" = 1 ]; then jok=true; fi
  if [ "$JSON" = 1 ]; then
    if [ -n "$CHECKS_JSON" ]; then CHECKS_JSON="$CHECKS_JSON,"; fi
    CHECKS_JSON="${CHECKS_JSON}{\"id\":$(json_str "$id"),\"ok\":$jok"
    if [ -n "$value" ]; then CHECKS_JSON="$CHECKS_JSON,\"value\":$(json_str "$value")"; fi
    if [ -n "$hint" ];  then CHECKS_JSON="$CHECKS_JSON,\"hint\":$(json_str "$hint")"; fi
    CHECKS_JSON="$CHECKS_JSON}"
  else
    if [ "$ok" = 1 ]; then
      printf '   ✓ %s%s\n' "$id" "${value:+ — $value}" >&"$LOG_FD"
    else
      printf '   ✗ %s — %s\n' "$id" "$hint" >&"$LOG_FD"
    fi
  fi
  if [ "$ok" != 1 ]; then
    if [ "$sev" = 4 ]; then FLAG4=1; else FLAG3=1; fi
  fi
}

run_preflight() {
  say "preflight${MODE:+ — mode: $MODE}"
  if command -v docker >/dev/null 2>&1; then
    check docker-cli 1 "" "found"
  else
    check docker-cli 0 "install Docker first (macOS: brew install colima docker)" "" 3
  fi
  if command -v docker >/dev/null 2>&1 && docker compose version >/dev/null 2>&1; then
    check docker-compose 1 "" "found"
  else
    check docker-compose 0 "install the docker compose plugin" "" 3
  fi
  # A stopped daemon is not fatal: setup auto-starts colima when it is installed.
  local daemon_ok=0 daemon_val=""
  if command -v docker >/dev/null 2>&1 && docker info >/dev/null 2>&1; then
    daemon_ok=1; daemon_val="running"
  elif command -v colima >/dev/null 2>&1; then
    daemon_ok=1; daemon_val="stopped (colima start runs during setup)"
  fi
  check docker-daemon "$daemon_ok" "start Docker Desktop, or: brew install colima && colima start" "$daemon_val" 3

  # Port free, or already held by our own container on the default port.
  local running="" owner="" port_ok=1 port_val="free"
  if command -v docker >/dev/null 2>&1; then
    running="$(docker ps --filter name=ntfy-ntfy -q 2>/dev/null || true)"
  fi
  if [ -n "$running" ] && [ "$NTFY_PORT" = 80 ]; then
    port_val="held by the running ntfy container (ok)"
  else
    owner="$(port_owner "$NTFY_PORT")"
    if [ -n "$owner" ]; then port_ok=0; port_val="in use by $owner"; fi
  fi
  check "port-$NTFY_PORT" "$port_ok" "stop that process, or set NTFY_PORT to a free port (e.g. NTFY_PORT=8080)" "$port_val" 4

  # Mode-specific checks (only the selected mode is assessed and scored).
  case "$MODE" in
    local)
      local lan="${LAN_IP:-}"
      if [ -z "$lan" ] && command -v ipconfig >/dev/null 2>&1; then
        lan="$(ipconfig getifaddr en0 2>/dev/null || ipconfig getifaddr en1 2>/dev/null || true)"
      fi
      if [ -z "$lan" ] && command -v hostname >/dev/null 2>&1; then
        lan="$(hostname -I 2>/dev/null | awk '{print $1}' || true)"
      fi
      if [ -n "$lan" ]; then
        check lan-ip 1 "" "$lan"
      else
        check lan-ip 0 "could not auto-detect — set it manually in $DATA_DIR/etc/server.yml" "" 3
      fi
      ;;
    tailscale)
      local ts=""
      ts="$(command -v tailscale || true)"
      for c in /opt/homebrew/bin/tailscale /usr/local/bin/tailscale; do
        if [ -z "$ts" ] && [ -x "$c" ]; then ts="$c"; fi
      done
      if [ -z "$ts" ]; then
        check tailscale-cli 0 "install: brew install tailscale (or the macOS app)" "" 3
        check tailscale-login 0 "install tailscale first" "" 3
      else
        check tailscale-cli 1 "" "$ts"
        if "$ts" status >/dev/null 2>&1; then
          check tailscale-login 1 "" "logged in"
        else
          check tailscale-login 0 "not logged in — run: tailscale up (finish in the browser)" "" 3
        fi
      fi
      ;;
    cloudflare)
      local cf=""
      cf="$(command -v cloudflared || true)"
      if [ -n "$cf" ]; then
        check cloudflared-cli 1 "" "$cf"
      else
        check cloudflared-cli 0 "install: brew install cloudflared" "" 3
      fi
      if [ -f "$HOME/.cloudflared/cert.pem" ]; then
        check cloudflared-login 1 "" "logged in"
      else
        check cloudflared-login 0 "not logged in — run: cloudflared login (browser)" "" 3
      fi
      if [ -n "$CF_HOSTNAME" ]; then
        check cloudflare-hostname 1 "" "$CF_HOSTNAME"
      else
        check cloudflare-hostname 0 "set CF_HOSTNAME=ntfy.example.com" "" 3
      fi
      ;;
  esac

  local code=0
  if [ "$FLAG4" = 1 ]; then code=4; fi
  if [ "$FLAG3" = 1 ] && [ "$code" = 0 ]; then code=3; fi
  if [ "$JSON" = 1 ]; then
    local okj=false
    if [ "$code" = 0 ]; then okj=true; fi
    printf '{"ok":%s,"kind":"preflight","mode":%s,"port":%d,"checks":[%s]}\n' \
      "$okj" "$(mode_json)" "$((10#$NTFY_PORT))" "$CHECKS_JSON"
  else
    if [ "$code" = 0 ]; then
      say "preflight OK${MODE:+ — ready for mode: $MODE}"
    else
      say "preflight FAILED (exit code $code)"
    fi
  fi
  exit "$code"
}

if [ "$CMD" = "preflight" ]; then
  run_preflight
fi

# ---------------------------------------------------------------- mode selection
if [ -z "$MODE" ]; then
  [ -t 0 ] || die 2 "usage: $0 [--json] local|tailscale|cloudflare (non-interactive)"
  printf 'How should your phone reach the ntfy server?\n' >&"$LOG_FD"
  printf '  1) local      — same Wi-Fi only (simplest, http://<LAN-IP>)\n' >&"$LOG_FD"
  printf '  2) tailscale  — private VPN, works anywhere (https://<machine>.ts.net)\n' >&"$LOG_FD"
  printf '  3) cloudflare — public URL via Cloudflare Tunnel (https://ntfy.example.com)\n' >&"$LOG_FD"
  printf 'Choice [1-3]: ' >&"$LOG_FD"
  read -r choice || die 2 "no input"
  case "$choice" in
    1) MODE=local ;; 2) MODE=tailscale ;; 3) MODE=cloudflare ;;
    *) die 2 "invalid choice: $choice" ;;
  esac
fi
case "$MODE" in local|tailscale|cloudflare) ;; *) die 2 "unknown mode: $MODE (local|tailscale|cloudflare)" ;; esac
say "mode: $MODE"

# ---------------------------------------------------------------- preflight
command -v docker >/dev/null 2>&1 || die 3 "docker not found — install it first (macOS: brew install colima docker && colima start)"
docker compose version >/dev/null 2>&1 || die 3 "'docker compose' plugin not found"
if ! docker info >/dev/null 2>&1; then
  if command -v colima >/dev/null 2>&1; then
    info "starting colima..."
    colima start || die 3 "colima failed to start"
  else
    die 3 "docker daemon not running"
  fi
fi

# Port availability — our own container on the default port means a re-run,
# anything else on the chosen port must be surfaced BEFORE any file writes.
RUNNING="$(docker ps --filter name=ntfy-ntfy -q 2>/dev/null || true)"
if [ -n "$RUNNING" ] && [ "$NTFY_PORT" = 80 ]; then
  info "port 80 held by the running ntfy container (re-run) — ok"
else
  OWNER="$(port_owner "$NTFY_PORT")"
  if [ -n "$OWNER" ]; then
    die 4 "port $NTFY_PORT is already in use by '$OWNER' — stop it, or re-run with NTFY_PORT set to a free port (e.g. NTFY_PORT=8080)"
  fi
fi

# Best-effort IANA timezone for the container.
detect_tz() {
  local tz
  tz="$(readlink /etc/localtime 2>/dev/null | sed 's|.*zoneinfo/||' || true)"
  [ -z "$tz" ] && tz="$(timedatectl show -p Timezone --value 2>/dev/null || true)"
  printf '%s' "${tz:-UTC}"
}
TZ_NAME="$(detect_tz)"

# ---------------------------------------------------------------- mode URL
BASE_URL=""
case "$MODE" in
  local)
    LAN_IP="${LAN_IP:-}"
    [ -z "$LAN_IP" ] && LAN_IP="$(ipconfig getifaddr en0 2>/dev/null || ipconfig getifaddr en1 2>/dev/null || true)"
    [ -z "$LAN_IP" ] && LAN_IP="$(hostname -I 2>/dev/null | awk '{print $1}' || true)"
    [ -z "$LAN_IP" ] && die 5 "could not detect LAN IP — set it manually in $DATA_DIR/etc/server.yml or via LAN_IP=<ip>"
    BASE_URL="http://$LAN_IP"
    if [ "$NTFY_PORT" != 80 ]; then BASE_URL="$BASE_URL:$NTFY_PORT"; fi
    ;;

  tailscale)
    TS="$(command -v tailscale || true)"
    for c in /opt/homebrew/bin/tailscale /usr/local/bin/tailscale; do
      [ -z "$TS" ] && [ -x "$c" ] && TS="$c"
    done
    [ -n "$TS" ] || die 3 "tailscale not installed — brew install tailscale (or use the macOS app from https://tailscale.com/download)"
    if ! "$TS" status >/dev/null 2>&1; then
      info "not logged in yet — starting 'tailscale up' (finish in your browser)..."
      "$TS" up >/dev/null 2>&1 || "$TS" up || die 3 "tailscale login failed"
    fi
    TS_HOST=""
    if command -v python3 >/dev/null 2>&1; then
      TS_HOST="$("$TS" status --json 2>/dev/null | python3 -c 'import json,sys; print(json.load(sys.stdin)["Self"]["DNSName"].rstrip("."))' 2>/dev/null || true)"
    fi
    [ -z "$TS_HOST" ] && TS_HOST="$("$TS" status --json 2>/dev/null | sed -n 's/.*"DNSName":"\([^"]*\)".*/\1/p' | head -1 | sed 's/\.$//')"
    [ -z "$TS_HOST" ] && die 5 "could not read Tailscale machine name (tailscale status --json)"
    BASE_URL="https://$TS_HOST"
    info "proxying port $NTFY_PORT → https://$TS_HOST via 'tailscale serve'..."
    if ! run_with_timeout 15 "$TS" serve --bg --https=443 "http://localhost:$NTFY_PORT"; then
      info "NOTE: if Serve is not yet active on your tailnet, open the activation"
      info "      link printed above (one-time admin approval), then re-run this script."
      info "      Manual equivalent: tailscale serve --bg --https=443 http://localhost:$NTFY_PORT"
      add_warning "tailscale-serve-pending" "Serve activation pending — approve the printed link, then re-run this script"
    fi
    ;;

  cloudflare)
    CF="$(command -v cloudflared || true)"
    [ -n "$CF" ] || die 3 "cloudflared not installed — brew install cloudflared"
    [ -f "$HOME/.cloudflared/cert.pem" ] || die 3 "not logged in to Cloudflare — run 'cloudflared login' first (browser), then re-run this script"
    if [ -z "$CF_HOSTNAME" ]; then
      [ -t 0 ] || die 3 "CF_HOSTNAME not set and no TTY to prompt for it"
      printf 'Public hostname for the tunnel (e.g. ntfy.example.com): ' >&"$LOG_FD"
      read -r CF_HOSTNAME || die 3 "no input for hostname"
      [ -z "$CF_HOSTNAME" ] && die 3 "hostname required"
    fi
    # Capture first — never pipe a writer into an early-exit reader under pipefail.
    CF_LIST="$("$CF" tunnel list 2>/dev/null || true)"
    if ! printf '%s\n' "$CF_LIST" | awk '{print $2}' | grep -qx "ntfy"; then
      info "creating Cloudflare tunnel 'ntfy'..."
      "$CF" tunnel create ntfy >/dev/null || die 5 "could not create Cloudflare tunnel 'ntfy'"
      CF_LIST="$("$CF" tunnel list 2>/dev/null || true)"
    fi
    TUNNEL_UUID="$(printf '%s\n' "$CF_LIST" | awk '$2=="ntfy" {print $1; exit}')"
    [ -z "$TUNNEL_UUID" ] && die 5 "could not determine tunnel UUID"
    # Dedicated config file so we never disturb other tunnels' config.yml.
    CF_CONFIG="$HOME/.cloudflared/ntfy.yml"
    cat > "$CF_CONFIG" <<EOF
$COMPOSE_MARKER
tunnel: $TUNNEL_UUID
credentials-file: $HOME/.cloudflared/$TUNNEL_UUID.json
ingress:
  - hostname: $CF_HOSTNAME
    service: http://localhost:$NTFY_PORT
  - service: http_status:404
EOF
    # -f overwrites an existing record on purpose. uninstall.sh deletes the
    # tunnel but keeps the DNS route, so a reinstall MUST re-point the hostname
    # at the new tunnel UUID — tolerating a failed route leaves it aimed at the
    # deleted tunnel, which Cloudflare answers with 530 (error 1033) forever.
    "$CF" tunnel route dns -f ntfy "$CF_HOSTNAME" >/dev/null 2>&1 \
      || die 5 "could not route $CF_HOSTNAME to tunnel 'ntfy'"
    BASE_URL="https://$CF_HOSTNAME"
    # Persistence: launchd on macOS (idempotent — skip if an existing agent
    # already runs this tunnel, e.g. a hand-installed LaunchAgent).
    PLIST="$HOME/Library/LaunchAgents/com.opencode-ntfy.cloudflared.plist"
    if [ "$(uname)" = "Darwin" ] && [ ! -f "$PLIST" ] \
      && ! grep -ls '<string>ntfy</string>' "$HOME"/Library/LaunchAgents/*.plist >/dev/null 2>&1; then
      cat > "$PLIST" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>Label</key><string>com.opencode-ntfy.cloudflared</string>
  <key>ProgramArguments</key><array>
    <string>$CF</string><string>tunnel</string><string>--config</string><string>$CF_CONFIG</string><string>run</string><string>ntfy</string>
  </array>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
  <key>StandardOutPath</key><string>$DATA_DIR/cloudflared.log</string>
  <key>StandardErrorPath</key><string>$DATA_DIR/cloudflared.log</string>
</dict></plist>
EOF
      launchctl bootstrap "gui/$(id -u)" "$PLIST" 2>/dev/null || launchctl load "$PLIST" 2>/dev/null || true
      info "persistence: LaunchAgent installed (runs at login, restarts on failure)"
    else
      info "persistence: existing cloudflared launch agent found (or non-macOS) — not duplicated"
    fi
    ;;
esac
say "base URL: $BASE_URL"

# ---------------------------------------------------------------- server files
mkdir -p "$DATA_DIR/etc" "$DATA_DIR/cache"
cat > "$DATA_DIR/docker-compose.yml" <<EOF
$COMPOSE_MARKER
services:
  ntfy:
    image: binwiederhier/ntfy
    command: serve
    container_name: ntfy-ntfy
    restart: unless-stopped
    init: true
    ports:
      - "$NTFY_PORT:80"
    environment:
      NTFY_BASE_URL: $BASE_URL
      TZ: $TZ_NAME
    volumes:
      - ./cache:/var/cache/ntfy
      - ./etc:/etc/ntfy
EOF

cat > "$DATA_DIR/etc/server.yml" <<EOF
$COMPOSE_MARKER
# Access mode: $MODE
# base-url MUST match the URL your phone subscribes with — the iOS instant-push
# wake-up signal is keyed to SHA256(base-url + "/" + topic).
base-url: "$BASE_URL"
cache-file: "/var/cache/ntfy/cache.db"
cache-duration: "24h"
# Auth: anonymous users may SUBSCRIBE (topic name = read secret) but may NOT
# publish. The plugin publishes with a token; the phone needs no credentials.
auth-file: "/var/cache/ntfy/user.db"
auth-default-access: "read-only"
# iOS background push: forward a poll request (message ID only, never content)
# to ntfy.sh, which wakes the phone via Firebase/APNS.
upstream-base-url: "https://ntfy.sh"
EOF

say "starting server"
cd "$DATA_DIR"
docker compose up -d >/dev/null
for i in $(seq 1 30); do
  if curl -fsS -m 3 "http://127.0.0.1:$NTFY_PORT/v1/health" >/dev/null 2>&1; then break; fi
  [ "$i" = 30 ] && die 5 "server did not become healthy — check: docker compose -f $DATA_DIR/docker-compose.yml logs"
  sleep 1
done
info "healthy"

# ---------------------------------------------------------------- user + token
USER_NAME="${NTFY_USER:-$USER}"
# NOTE: don't pipe `docker compose exec` straight into `grep -q` here — under
# `set -o pipefail`, grep's early exit SIGPIPEs docker and poisons the status.
user_exists() {
  local list
  list="$(docker compose exec -T ntfy ntfy user list 2>&1 || true)"
  case "$list" in
    "user $USER_NAME "* | *$'\n'"user $USER_NAME "*) return 0 ;;
  esac
  return 1
}

if user_exists; then
  info "user '$USER_NAME' already exists"
else
  PW_FILE="$DATA_DIR/.admin-password"
  if [ ! -f "$PW_FILE" ]; then
    openssl rand -base64 18 | tr -d '/+=' | head -c 24 > "$PW_FILE"
    chmod 600 "$PW_FILE"
  fi
  # May legitimately fail with "already exists" (race/duplicate) — verify after.
  docker compose exec -T -e "NTFY_PASSWORD=$(cat "$PW_FILE")" ntfy ntfy user add --role=admin "$USER_NAME" >/dev/null 2>&1 || true
  for _ in 1 2 3; do
    user_exists && break
    sleep 1
  done
  user_exists || die 5 "could not create user '$USER_NAME' — check: docker compose logs"
  info "user '$USER_NAME' ready (admin password: $PW_FILE)"
fi

TOKEN="$(docker compose exec -T ntfy ntfy token list "$USER_NAME" 2>&1 | grep -oE 'tk_[A-Za-z0-9_-]+' | head -1 || true)"
if [ -z "$TOKEN" ]; then
  TOKEN="$(docker compose exec -T ntfy ntfy token add --label="$TOKEN_LABEL" "$USER_NAME" 2>&1 | grep -oE 'tk_[A-Za-z0-9_-]+' | head -1 || true)"
fi
[ -n "$TOKEN" ] || die 5 "could not create/access an access token"
info "token: $TOKEN"

# A public URL trails provisioning: Cloudflare answers 530 (error 1033) until the
# new hostname is live at the edge, and Tailscale Serve's first request races
# proxy warm-up (SPEC §14.5). Poll instead of judging request #1.
# Sets PUB_CODE (not stdout — this reports progress, and a command substitution
# would swallow that line into the captured value).
public_publish() { # <url> <body>
  local try=1 tries=1
  case "$MODE" in cloudflare|tailscale) tries=15 ;; esac
  PUB_CODE=""
  while :; do
    PUB_CODE="$(curl -s -o /dev/null -w '%{http_code}' -m 10 -H "Authorization: Bearer $TOKEN" -d "$2" "$1" || true)"
    if [ "$PUB_CODE" = "200" ]; then break; fi
    if [ "$try" -ge "$tries" ]; then break; fi
    if [ "$try" = 1 ]; then info "waiting for $1 to answer (HTTP $PUB_CODE) — DNS/tunnel warm-up..."; fi
    try=$((try + 1))
    sleep 3
  done
}

# ---------------------------------------------------------------- smoke tests
say "smoking test auth"
ANON="$(curl -s -o /dev/null -w '%{http_code}' -m 5 -d 'anon' "http://127.0.0.1:$NTFY_PORT/opencode-setup-check" || true)"
[ "$ANON" = "403" ] || die 5 "anonymous publish should be denied (got HTTP $ANON — is auth-default-access correct?)"
AUTH="$(curl -s -o /dev/null -w '%{http_code}' -m 5 -H "Authorization: Bearer $TOKEN" -d 'ok' "http://127.0.0.1:$NTFY_PORT/opencode-setup-check" || true)"
[ "$AUTH" = "200" ] || die 5 "token publish failed (HTTP $AUTH)"
public_publish "$BASE_URL/opencode-setup-check" 'setup-ok'
PUB="$PUB_CODE"
if [ "$PUB" != "200" ]; then
  info "WARNING: publish via $BASE_URL returned HTTP $PUB (phone may not reach this URL yet)"
  add_warning "public-url-unreachable" "publish via $BASE_URL returned HTTP $PUB"
fi
info "anonymous publish: denied ($ANON) ✓   token publish: ok ($AUTH) ✓   via $BASE_URL: $PUB"

# ---------------------------------------------------------------- summary
if [ "$JSON" != 1 ]; then
  say "done — mode: $MODE, server: $BASE_URL"
  cat <<EOF

1) Add the plugin (opencode.json / ~/.config/opencode/opencode.json):

   "plugin": [
     ["/path/to/opencode-ntfy", { "serverUrl": "$BASE_URL", "token": "$TOKEN" }]
   ]

2) Start OpenCode once — the [ntfy] startup log prints your one topic
   (every event kind arrives on this single topic).

3) On your phone: install the ntfy app → default server = $BASE_URL
   → subscribe to that one topic. $( [ "$MODE" = "local" ] && echo "Phone must be on this Wi-Fi." )$( [ "$MODE" = "tailscale" ] && echo "Phone needs the Tailscale app (enable Settings → Tailscale → Connect on Demand)." )

   iOS instant push is pre-configured (upstream-base-url → ntfy.sh → APNS).

Switching modes later: re-run this script with another mode, then re-add the
subscriptions on the phone (they are keyed by server URL).
EOF
else
  printf '{"ok":true,"kind":"setup","mode":%s,"serverUrl":%s,"user":%s,"token":%s,"port":%d,"smoke":{"anon":%s,"tokenPublish":%s,"public":%s},"warnings":[%s]}\n' \
    "$(json_str "$MODE")" "$(json_str "$BASE_URL")" "$(json_str "$USER_NAME")" "$(json_str "$TOKEN")" \
    "$((10#$NTFY_PORT))" "$(json_str "$ANON")" "$(json_str "$AUTH")" "$(json_str "$PUB")" "$WARNINGS"
fi
