#!/usr/bin/env bash
#
# opencode-ntfy server setup — one command for all three access modes:
#
#   ./scripts/setup-server.sh local        # phone on the same Wi-Fi
#   ./scripts/setup-server.sh tailscale    # private tailnet, works anywhere
#   ./scripts/setup-server.sh cloudflare   # public URL via Cloudflare Tunnel
#
# What it does (idempotent — safe to re-run to switch modes):
#   1. writes ~/ntfy/docker-compose.yml + etc/server.yml for the chosen mode
#      (auth: anonymous read-only; upstream-base-url for iOS instant push)
#   2. starts the server (Docker; on macOS: Colima) and waits for health
#   3. creates an admin user + access token (reusing an existing one if present)
#   4. mode extras: tailscale serve proxy / cloudflared tunnel + DNS + launchd
#   5. smoke-tests auth (anonymous publish must be denied) and prints your
#      opencode.json snippet + phone instructions
#
# Switching modes later: re-run this script with the other mode, then
# re-add the subscriptions on your phone (they are keyed by server URL).
#
set -euo pipefail

MODE="${1:-}"
DATA_DIR="${NTFY_SETUP_DIR:-$HOME/ntfy}"
CF_HOSTNAME="${CF_HOSTNAME:-}"
TOKEN_LABEL="opencode-setup"
COMPOSE_MARKER="# generated by opencode-ntfy setup-server.sh"

say()  { printf '\n\033[1m== %s\033[0m\n' "$*"; }
info() { printf '   %s\n' "$*"; }
die()  { printf '\033[31mERROR:\033[0m %s\n' "$*" >&2; exit 1; }

# Run a command with a hard deadline. Needed because `tailscale serve --bg`
# BLOCKS forever when Serve isn't activated yet (it prints an activation link
# and then waits for approval that will never come in a non-interactive run).
# The perl fallback forks so bash never reports a signal-killed child.
run_with_timeout() {
  local secs="$1"; shift
  if command -v timeout >/dev/null 2>&1; then timeout "$secs" "$@"
  elif command -v gtimeout >/dev/null 2>&1; then gtimeout "$secs" "$@"
  else perl -e '
      my $secs = shift;
      my $pid = fork() // exit 127;
      if (!$pid) { exec @ARGV or exit 127 }
      local $SIG{ALRM} = sub { kill "TERM", $pid; exit 124 };
      alarm $secs;
      waitpid($pid, 0);
      my $st = $?;
      exit($st & 127 ? 128 + ($st & 127) : $st >> 8);
    ' "$secs" "$@"
  fi
}

# ---------------------------------------------------------------- mode selection
if [ -z "$MODE" ]; then
  [ -t 0 ] || die "usage: $0 local|tailscale|cloudflare (non-interactive)"
  printf 'How should your phone reach the ntfy server?\n'
  printf '  1) local      — same Wi-Fi only (simplest, http://<LAN-IP>)\n'
  printf '  2) tailscale  — private VPN, works anywhere (https://<machine>.ts.net)\n'
  printf '  3) cloudflare — public URL via Cloudflare Tunnel (https://ntfy.example.com)\n'
  printf 'Choice [1-3]: '
  read -r choice
  case "$choice" in
    1) MODE=local ;; 2) MODE=tailscale ;; 3) MODE=cloudflare ;;
    *) die "invalid choice: $choice" ;;
  esac
fi
case "$MODE" in local|tailscale|cloudflare) ;; *) die "unknown mode: $MODE (local|tailscale|cloudflare)" ;; esac
say "mode: $MODE"

# ---------------------------------------------------------------- preflight
command -v docker >/dev/null 2>&1 || die "docker not found — install it first (macOS: brew install colima docker && colima start)"
docker compose version >/dev/null 2>&1 || die "'docker compose' plugin not found"
if ! docker info >/dev/null 2>&1; then
  if command -v colima >/dev/null 2>&1; then info "starting colima..."; colima start; else die "docker daemon not running"; fi
fi

# Best-effort IANA timezone for the container.
detect_tz() {
  local tz
  tz="$(readlink /etc/localtime 2>/dev/null | sed 's|.*zoneinfo/||' || true)"
  [ -z "$tz" ] && tz="$(timedatectl show -p Timezone --value 2>/dev/null || true)"
  printf '%s' "${tz:-UTC}"
}
TZ_NAME="$(detect_tz)"

# ---------------------------------------------------------------- mode URL
BASE_URL=""
case "$MODE" in
  local)
    LAN_IP="$(ipconfig getifaddr en0 2>/dev/null || ipconfig getifaddr en1 2>/dev/null || true)"
    [ -z "$LAN_IP" ] && LAN_IP="$(hostname -I 2>/dev/null | awk '{print $1}' || true)"
    [ -z "$LAN_IP" ] && die "could not detect LAN IP — set it manually in $DATA_DIR/etc/server.yml"
    BASE_URL="http://$LAN_IP"
    ;;

  tailscale)
    TS="$(command -v tailscale || true)"
    for c in /opt/homebrew/bin/tailscale /usr/local/bin/tailscale; do
      [ -z "$TS" ] && [ -x "$c" ] && TS="$c"
    done
    [ -n "$TS" ] || die "tailscale not installed — brew install tailscale (or use the macOS app from https://tailscale.com/download)"
    if ! "$TS" status >/dev/null 2>&1; then
      info "not logged in yet — starting 'tailscale up' (finish in your browser)..."
      "$TS" up >/dev/null 2>&1 || "$TS" up || die "tailscale login failed"
    fi
    TS_HOST=""
    if command -v python3 >/dev/null 2>&1; then
      TS_HOST="$("$TS" status --json 2>/dev/null | python3 -c 'import json,sys; print(json.load(sys.stdin)["Self"]["DNSName"].rstrip("."))' 2>/dev/null || true)"
    fi
    [ -z "$TS_HOST" ] && TS_HOST="$("$TS" status --json 2>/dev/null | sed -n 's/.*"DNSName":"\([^"]*\)".*/\1/p' | head -1 | sed 's/\.$//')"
    [ -z "$TS_HOST" ] && die "could not read Tailscale machine name (tailscale status --json)"
    BASE_URL="https://$TS_HOST"
    info "proxying port 80 → https://$TS_HOST via 'tailscale serve'..."
    if ! run_with_timeout 15 "$TS" serve --bg --https=443 http://localhost:80; then
      info "NOTE: if Serve is not yet active on your tailnet, open the activation"
      info "      link printed above (one-time admin approval), then re-run this script."
      info "      Manual equivalent: tailscale serve --bg --https=443 http://localhost:80"
    fi
    ;;

  cloudflare)
    CF="$(command -v cloudflared || true)"
    [ -n "$CF" ] || die "cloudflared not installed — brew install cloudflared"
    [ -f "$HOME/.cloudflared/cert.pem" ] || die "not logged in to Cloudflare — run 'cloudflared login' first (browser), then re-run this script"
    if [ -z "$CF_HOSTNAME" ]; then
      [ -t 0 ] || die "CF_HOSTNAME not set and no TTY to prompt for it"
      printf 'Public hostname for the tunnel (e.g. ntfy.example.com): '
      read -r CF_HOSTNAME
      [ -z "$CF_HOSTNAME" ] && die "hostname required"
    fi
    # Capture first — never pipe a writer into an early-exit reader under pipefail.
    CF_LIST="$("$CF" tunnel list 2>/dev/null || true)"
    if ! printf '%s\n' "$CF_LIST" | awk '{print $2}' | grep -qx "ntfy"; then
      info "creating Cloudflare tunnel 'ntfy'..."
      "$CF" tunnel create ntfy >/dev/null
      CF_LIST="$("$CF" tunnel list 2>/dev/null || true)"
    fi
    TUNNEL_UUID="$(printf '%s\n' "$CF_LIST" | awk '$2=="ntfy" {print $1; exit}')"
    [ -z "$TUNNEL_UUID" ] && die "could not determine tunnel UUID"
    # Dedicated config file so we never disturb other tunnels' config.yml.
    CF_CONFIG="$HOME/.cloudflared/ntfy.yml"
    cat > "$CF_CONFIG" <<EOF
$COMPOSE_MARKER
tunnel: $TUNNEL_UUID
credentials-file: $HOME/.cloudflared/$TUNNEL_UUID.json
ingress:
  - hostname: $CF_HOSTNAME
    service: http://localhost:80
  - service: http_status:404
EOF
    "$CF" tunnel route dns ntfy "$CF_HOSTNAME" 2>/dev/null \
      || info "(DNS record for $CF_HOSTNAME already exists — ok)"
    BASE_URL="https://$CF_HOSTNAME"
    # Persistence: launchd on macOS (idempotent — skip if an existing agent
    # already runs this tunnel, e.g. a hand-installed LaunchAgent).
    PLIST="$HOME/Library/LaunchAgents/com.opencode-ntfy.cloudflared.plist"
    if [ "$(uname)" = "Darwin" ] && [ ! -f "$PLIST" ] \
      && ! grep -ls '<string>ntfy</string>' "$HOME"/Library/LaunchAgents/*.plist >/dev/null 2>&1; then
      cat > "$PLIST" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>Label</key><string>com.opencode-ntfy.cloudflared</string>
  <key>ProgramArguments</key><array>
    <string>$CF</string><string>tunnel</string><string>--config</string><string>$CF_CONFIG</string><string>run</string><string>ntfy</string>
  </array>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
  <key>StandardOutPath</key><string>$DATA_DIR/cloudflared.log</string>
  <key>StandardErrorPath</key><string>$DATA_DIR/cloudflared.log</string>
</dict></plist>
EOF
      launchctl bootstrap "gui/$(id -u)" "$PLIST" 2>/dev/null || launchctl load "$PLIST" 2>/dev/null || true
      info "persistence: LaunchAgent installed (runs at login, restarts on failure)"
    else
      info "persistence: existing cloudflared launch agent found (or non-macOS) — not duplicated"
    fi
    ;;
esac
say "base URL: $BASE_URL"

# ---------------------------------------------------------------- server files
mkdir -p "$DATA_DIR/etc" "$DATA_DIR/cache"
cat > "$DATA_DIR/docker-compose.yml" <<EOF
$COMPOSE_MARKER
services:
  ntfy:
    image: binwiederhier/ntfy
    command: serve
    container_name: ntfy-ntfy
    restart: unless-stopped
    init: true
    ports:
      - "80:80"
    environment:
      NTFY_BASE_URL: $BASE_URL
      TZ: $TZ_NAME
    volumes:
      - ./cache:/var/cache/ntfy
      - ./etc:/etc/ntfy
EOF

cat > "$DATA_DIR/etc/server.yml" <<EOF
$COMPOSE_MARKER
# Access mode: $MODE
# base-url MUST match the URL your phone subscribes with — the iOS instant-push
# wake-up signal is keyed to SHA256(base-url + "/" + topic).
base-url: "$BASE_URL"
cache-file: "/var/cache/ntfy/cache.db"
cache-duration: "24h"
# Auth: anonymous users may SUBSCRIBE (topic name = read secret) but may NOT
# publish. The plugin publishes with a token; the phone needs no credentials.
auth-file: "/var/cache/ntfy/user.db"
auth-default-access: "read-only"
# iOS background push: forward a poll request (message ID only, never content)
# to ntfy.sh, which wakes the phone via Firebase/APNS.
upstream-base-url: "https://ntfy.sh"
EOF

say "starting server"
cd "$DATA_DIR"
docker compose up -d >/dev/null
for i in $(seq 1 30); do
  if curl -fsS -m 3 http://127.0.0.1/v1/health >/dev/null 2>&1; then break; fi
  [ "$i" = 30 ] && die "server did not become healthy — check: docker compose -f $DATA_DIR/docker-compose.yml logs"
  sleep 1
done
info "healthy"

# ---------------------------------------------------------------- user + token
USER_NAME="${NTFY_USER:-$USER}"
# NOTE: don't pipe `docker compose exec` straight into `grep -q` here — under
# `set -o pipefail`, grep's early exit SIGPIPEs docker and poisons the status.
user_exists() {
  local list
  list="$(docker compose exec -T ntfy ntfy user list 2>&1 || true)"
  case "$list" in
    "user $USER_NAME "* | *$'\n'"user $USER_NAME "*) return 0 ;;
  esac
  return 1
}

if user_exists; then
  info "user '$USER_NAME' already exists"
else
  PW_FILE="$DATA_DIR/.admin-password"
  if [ ! -f "$PW_FILE" ]; then
    openssl rand -base64 18 | tr -d '/+=' | head -c 24 > "$PW_FILE"
    chmod 600 "$PW_FILE"
  fi
  # May legitimately fail with "already exists" (race/duplicate) — verify after.
  docker compose exec -T -e "NTFY_PASSWORD=$(cat "$PW_FILE")" ntfy ntfy user add --role=admin "$USER_NAME" >/dev/null 2>&1 || true
  for _ in 1 2 3; do
    user_exists && break
    sleep 1
  done
  user_exists || die "could not create user '$USER_NAME' — check: docker compose logs"
  info "user '$USER_NAME' ready (admin password: $PW_FILE)"
fi

TOKEN="$(docker compose exec -T ntfy ntfy token list "$USER_NAME" 2>&1 | grep -oE 'tk_[A-Za-z0-9_-]+' | head -1 || true)"
if [ -z "$TOKEN" ]; then
  TOKEN="$(docker compose exec -T ntfy ntfy token add --label="$TOKEN_LABEL" "$USER_NAME" 2>&1 | grep -oE 'tk_[A-Za-z0-9_-]+' | head -1 || true)"
fi
[ -n "$TOKEN" ] || die "could not create/access an access token"
info "token: $TOKEN"

# ---------------------------------------------------------------- smoke tests
say "smoking test auth"
ANON="$(curl -s -o /dev/null -w '%{http_code}' -m 5 -d 'anon' http://127.0.0.1/opencode-setup-check || true)"
[ "$ANON" = "403" ] || die "anonymous publish should be denied (got HTTP $ANON — is auth-default-access correct?)"
AUTH="$(curl -s -o /dev/null -w '%{http_code}' -m 5 -H "Authorization: Bearer $TOKEN" -d 'ok' http://127.0.0.1/opencode-setup-check || true)"
[ "$AUTH" = "200" ] || die "token publish failed (HTTP $AUTH)"
PUB="$(curl -s -o /dev/null -w '%{http_code}' -m 10 -H "Authorization: Bearer $TOKEN" -d 'setup-ok' "$BASE_URL/opencode-setup-check" || true)"
[ "$PUB" = "200" ] || info "WARNING: publish via $BASE_URL returned HTTP $PUB (phone may not reach this URL yet)"
info "anonymous publish: denied (403) ✓   token publish: ok (200) ✓   via $BASE_URL: $PUB"

# ---------------------------------------------------------------- summary
say "done — mode: $MODE, server: $BASE_URL"
cat <<EOF

1) Add the plugin (opencode.json / ~/.config/opencode/opencode.json):

   "plugin": [
     ["/path/to/opencode-ntfy", { "serverUrl": "$BASE_URL", "token": "$TOKEN" }]
   ]

2) Start OpenCode once — the [ntfy] startup log prints your one topic
   (every event kind arrives on this single topic).

3) On your phone: install the ntfy app → default server = $BASE_URL
   → subscribe to that one topic. $( [ "$MODE" = "local" ] && echo "Phone must be on this Wi-Fi." )$( [ "$MODE" = "tailscale" ] && echo "Phone needs the Tailscale app (enable Settings → Tailscale → Connect on Demand)." )

   iOS instant push is pre-configured (upstream-base-url → ntfy.sh → APNS).

Switching modes later: re-run this script with another mode, then re-add the
subscriptions on the phone (they are keyed by server URL).
EOF
